export type Difficulty = "easy" | "medium" | "hard";

export const DIFF_CONFIG: Record<Difficulty, { label: string; age: string; emoji: string; length: number; guesses: number }> = {
  easy:   { label: "Easy",   age: "Age 8+",  emoji: "😊", length: 4, guesses: 6 },
  medium: { label: "Medium", age: "Age 10+", emoji: "🤔", length: 5, guesses: 6 },
  hard:   { label: "Hard",   age: "Age 15+", emoji: "💀", length: 6, guesses: 6 },
};

// ── 4-letter words (Easy — age 8+) ──────────────────────────────────
const EASY: string[] = [
  "ball","band","bank","barn","bath","bear","beat","bell","belt","best",
  "bike","bird","blow","blue","boat","bold","bolt","bone","book","boom",
  "boot","born","boss","bowl","bump","burn","bush","busy","buzz","cafe",
  "cage","cake","calf","calm","camp","cape","card","care","cart","cash",
  "cast","cave","chef","chip","clam","clap","claw","clay","clip","club",
  "clue","coal","coat","coil","cold","come","cook","cool","copy","cord",
  "corn","cost","cozy","crab","crew","crop","crow","cube","curl","cute",
  "dark","dash","data","date","dawn","days","dead","deal","dear","deck",
  "deep","deer","dell","dent","desk","dial","dice","diet","dill","dime",
  "dirt","disk","dive","dock","dome","door","dose","dote","dove","down",
  "drag","draw","drip","drop","drum","dusk","dust","each","earl","earn",
  "ease","east","edge","eggs","epic","face","fact","fade","fail","fair",
  "fall","fame","farm","fast","fate","fear","feel","feet","fell","fern",
  "fill","film","find","fire","firm","fish","fist","fizz","flag","flat",
  "flaw","flip","flow","foam","fold","folk","fond","font","foot","ford",
  "fork","form","fort","frog","from","fuel","full","fund","fuse","gale",
  "game","gang","gate","gave","gaze","gear","germ","gift","give","glad",
  "glow","glue","gold","golf","good","gown","grab","gram","grip","gust",
  "hail","half","hall","halt","hand","hard","hare","harp","head","heal",
  "heap","heat","heel","help","herb","hero","hide","high","hill","hint",
  "hold","hole","home","hood","hook","hope","horn","hose","hour","huge",
  "hull","hump","hunt","hurt","hush","icon","idea","idle","iris","iron",
  "isle","itch","item","jade","jail","jolt","jump","just","keen","kept",
  "kick","kind","king","kiss","kite","knot","lake","lamp","land","lark",
  "last","late","lawn","lead","leaf","lean","left","lime","line","link",
  "lion","list","load","lock","loft","long","look","loop","lore","lost",
  "love","luck","lung","lure","made","mail","main","make","mane","mark",
  "mars","mash","mask","mate","maze","meal","mean","meat","meet","melt",
  "mesh","mild","milk","mill","mind","mine","mint","mist","mode","mole",
  "mood","moon","more","moss","most","moth","much","mule","myth","nail",
  "name","nape","navy","near","neck","need","nest","news","next","nice",
  "nine","node","noon","nose","note","null","oath","once","open","page",
  "pain","palm","park","part","pass","past","path","peak","peel","peg",
  "perk","pest","pick","pier","pile","pill","pine","pink","pipe","pity",
  "plan","play","plot","plow","plug","plum","plus","poem","polo","pond",
  "pool","poor","pore","port","pose","post","pour","prey","prop","pull",
  "pump","pure","push","quit","quiz","race","rack","rage","rail","rain",
  "rake","ramp","rang","rank","rave","read","real","reel","rely","rice",
  "rich","ride","rind","ring","riot","rise","risk","road","roam","roar",
  "robe","rock","rode","role","roll","roof","room","rope","rose","rule",
  "rush","rust","safe","sage","sail","sale","salt","sand","sane","sang",
  "sank","save","scan","scar","seal","seam","seed","seek","seem","self",
  "sell","shed","ship","shoe","shop","shot","show","shut","sick","sigh",
  "silk","sing","sink","site","size","skin","skip","slam","slim","slip",
  "slow","slug","snap","snow","soap","sock","soft","soil","sole","some",
  "song","soon","sore","soul","soup","span","spin","spit","spot","spur",
  "star","stay","stem","step","stir","stop","stub","such","suit","sung",
  "sunk","swap","swim","tail","tale","tall","tame","tank","tape","tart",
  "task","taxi","team","tear","tell","tent","term","test","thin","thorn",
  "tide","tied","tile","till","time","tiny","tire","toad","told","toll",
  "tomb","tone","tool","tops","tore","town","trap","tray","tree","trek",
  "trim","trio","trip","trot","true","tube","tuck","tune","turf","turn",
  "tusk","twin","type","ugly","undo","upon","used","vale","vane","vary",
  "vast","veil","very","vest","view","vine","void","volt","vote","wade",
  "wage","wake","walk","wall","ward","warm","warn","warp","wart","wave",
  "weak","weed","week","well","west","whip","wide","wild","will","wilt",
  "wind","wine","wing","wink","wire","wise","wish","wolf","wood","wool",
  "word","wore","work","worm","worn","wove","wrap","wren","writ","yard",
  "yarn","yawn","year","yell","yoga","yolk","your","zeal","zero","zone",
];

// ── 5-letter words (Medium — age 10+) ───────────────────────────────
const MEDIUM: string[] = [
  "abide","above","abuse","acorn","actor","adapt","admit","adopt","adult","affix",
  "after","again","aisle","alarm","album","alert","algae","alien","align","alike",
  "alive","aloft","alone","aloof","aloud","altar","alter","angel","anger","angle",
  "angry","anime","ankle","annex","apart","apple","apply","apron","arena","argue",
  "arise","armor","aroma","arose","array","arrow","arson","asset","atlas","attic",
  "audit","avoid","awake","award","aware","awful","azure","badge","badly","basic",
  "basis","batch","beach","beard","began","begin","being","below","bench","billy",
  "bingo","birch","black","blade","blame","bland","blaze","bleat","blend","bless",
  "blind","blink","block","blood","bloom","blown","board","boast","booze","bound",
  "boxer","brace","braid","brake","brand","brave","bread","break","breed","brick",
  "bride","brief","brine","bring","brisk","broad","brook","broom","broth","brown",
  "bruise","budge","build","built","bulge","bully","bunch","bunny","burst","cabin",
  "camel","candy","cargo","carry","catch","cause","cedar","chair","chalk","chaos",
  "charm","chase","cheap","check","cheek","cheer","chess","chest","chief","child",
  "chill","china","chord","churn","civil","clank","class","clean","clear","clerk",
  "cliff","cling","close","cloth","cloud","clown","comet","comic","comma","coral",
  "cough","could","count","court","cover","crack","craft","crane","crash","crazy",
  "cream","creek","crime","crisp","cross","crowd","crown","crust","cubic","curve",
  "cycle","daily","dairy","dance","decay","delay","delta","dense","depot","depth",
  "derby","devil","digit","dirty","disco","ditch","ditzy","dizzy","dodge","doing",
  "dolly","donor","doubt","dough","downy","draft","drain","drama","drank","drawn",
  "dream","dress","dried","drift","drill","drive","drone","drove","dwarf","eager",
  "early","earth","eight","elite","empty","endow","enemy","enjoy","enter","envoy",
  "equal","error","essay","evade","event","every","exact","exist","extra","fable",
  "faced","faith","fancy","feast","fence","ferry","fetch","fever","fewer","fiber",
  "field","fifth","fifty","fight","final","first","fixed","flame","flash","flesh",
  "flock","flood","floor","flora","floss","flour","fluid","flute","focal","focus",
  "force","forge","forth","found","frame","frank","fraud","fresh","front","frost",
  "froze","fruit","fully","funny","gauge","ghost","given","gland","glare","glass",
  "glaze","gleam","gloom","gloss","grace","grade","grain","grand","grant","graze",
  "greed","greet","grief","groan","grope","gross","group","grove","growl","grown",
  "gruel","gruff","guard","guide","guild","guile","guise","gusto","gypsy","habit",
  "happy","harsh","haste","hatch","haven","hazel","heart","heavy","hedge","heron",
  "hinge","hippo","hoist","holly","honor","horse","hotel","hound","human","humid",
  "humor","hurry","hyper","ideal","image","imply","index","indie","infer","inner",
  "input","inter","intro","irony","ivory","jewel","joker","joust","juice","juicy",
  "jumbo","karma","kazoo","kebab","kneel","knife","knock","known","koala","label",
  "lance","large","laser","latch","later","layer","learn","lease","least","ledge",
  "legal","lemon","level","light","lilac","liver","lofty","logic","loose","lotus",
  "lower","loyal","lucid","lunar","lusty","lyric","magic","major","maker","manor",
  "maple","march","marry","match","mayor","media","mercy","merit","metal","meter",
  "micro","might","mimic","minor","minus","mirth","miser","mixer","model","moist",
  "money","monks","moral","motor","motto","mount","mourn","mouse","mouth","movie",
  "muddy","murky","music","musty","muted","naive","nifty","night","noble","noise",
  "north","noted","novel","nudge","nurse","nymph","ocean","offer","often","olive",
  "onset","opera","optic","orbit","order","otter","ought","outer","ovary","owned",
  "oxide","ozone","paced","paint","panic","paper","pasta","paste","patch","pearl",
  "pedal","penny","perch","peril","phase","piano","pilot","pinch","pitch","pixel",
  "pizza","place","plain","plane","plant","plate","plaza","plead","pleat","plump",
  "plunk","point","poker","polar","polka","posed","power","press","price","pride",
  "prime","print","prize","probe","prone","proof","prose","proud","prove","psalm",
  "queen","query","queue","quick","quiet","quota","quote","radar","radio","raise",
  "rally","ramen","rapid","ratio","razor","reach","realm","rebel","reign","relax",
  "repay","repel","reply","reuse","rider","ridge","ripen","risen","river","robin",
  "robot","rocky","rouge","rough","round","rouse","route","rover","rowdy","royal",
  "rugby","ruler","rural","sadly","saint","salad","sauce","savor","scald","scale",
  "scamp","scene","scone","score","scorn","scout","screw","scrub","seize","serve",
  "seven","shack","shade","shake","shall","shame","shape","share","shark","sharp",
  "shear","sheep","sheer","shelf","shell","shift","shine","shirt","shore","short",
  "shout","shove","sight","silly","since","sixth","sixty","sized","skate","skill",
  "skull","slang","slash","slate","sleek","sleep","sleet","slept","slice","slide",
  "slime","slope","sloth","smart","smash","smell","smirk","smoke","snail","snake",
  "snare","sneak","sniff","solve","sonic","sorry","south","space","spare","spark",
  "spawn","speak","spear","speed","spell","spice","spike","spine","spite","split",
  "spoke","spoon","spore","sport","spray","sprig","squad","squat","squid","stack",
  "stage","stain","stale","stall","stamp","stand","stare","stark","start","state",
  "stave","steal","steam","steel","steep","steer","stick","still","stock","stomp",
  "stone","stood","store","stork","storm","story","stout","stove","strap","straw",
  "stray","strip","stuck","study","stuff","stump","stunt","style","sugar","suite",
  "sunny","super","surge","swamp","swear","sweat","sweep","sweet","swept","swift",
  "swing","swipe","swirl","sword","sworn","syrup","tabby","table","talon","taste",
  "teach","tease","teeth","tempo","tense","tepid","thick","third","thorn","those",
  "three","threw","throw","thrum","thumb","thump","tiger","tiled","tired","title",
  "today","token","tonic","topaz","topic","torch","total","touch","tough","towel",
  "tower","toxic","trace","track","trade","trail","train","trait","tramp","trout",
  "truce","truck","truly","trump","trunk","trust","truth","tulip","tumor","tuner",
  "twirl","twist","ultra","unify","union","unity","until","usage","usual","utter",
  "vague","valid","value","valve","vapid","vault","vicar","vigor","viral","virus",
  "visit","vista","vivid","vocal","voice","voter","vowel","waged","water","weave",
  "wedge","weedy","weigh","weird","whale","wheat","wheel","where","which","while",
  "white","whole","whose","widen","widow","windy","witty","women","world","worry",
  "worse","worst","would","wrist","wrong","yacht","yeast","yield","young","yours",
  "youth","zebra","zesty","zippy","zombi",
];

// ── 6-letter words (Hard — age 15+) ─────────────────────────────────
const HARD: string[] = [
  "absent","absorb","accent","access","accord","accuse","aching","across","acting","action",
  "actual","adjoin","affirm","afford","afraid","agency","agenda","agreed","alight","allied",
  "allure","almost","almond","alpine","ambush","amiable","amount","amused","anchor","anneal",
  "annual","anoint","answer","anthem","antics","antler","anyone","apathy","appear","arcade",
  "ardent","argued","arisen","around","arouse","artful","artist","ascend","aspect","aspire",
  "assert","assist","assume","assure","attain","attend","attire","august","aurora","author",
  "autumn","avenue","averse","avocet","awoken","babble","badger","baffle","ballet","ballot",
  "bandit","barren","barter","battle","beacon","beaker","beckon","behave","belief","belong",
  "bestow","betray","bitter","blazer","bleach","blight","blithe","bother","bottle","bounce",
  "braver","breach","breath","brevet","bridge","bright","brimly","broken","bronze","burrow",
  "cactus","candle","cannon","canyon","canvas","career","carrot","casual","caught","cavern",
  "censor","center","cereal","charge","chrome","circle","clamor","clasp","clever","combat",
  "coerce","coffee","colony","combat","comedy","common","concur","danger","dapper","darken",
  "daunts","debris","decent","deceive","define","delete","deluge","demand","demise","denote",
  "depict","derive","desert","design","devour","differ","divert","domain","donate","donkey",
  "double","driven","dwindle","earnest","effort","either","embark","emerge","empire","enable",
  "entail","entire","escape","estate","ethics","evolve","exceed","excite","exempt","exhort",
  "exiled","exotic","expand","expect","expire","export","expose","extend","factor","famine",
  "fasten","fathom","feline","fester","fickle","fierce","figure","finale","finger","finite",
  "flaunt","flight","flinch","flutter","follow","forbid","forget","formal","foster","freely",
  "frenzy","frozen","future","garlic","garner","gentle","geyser","gibber","giggle","glacial",
  "glance","glimmer","glitch","global","goblin","gossip","gravel","grovel","growth","grumpy",
  "hamper","handle","happen","harbor","hardly","hasten","hatred","hazard","health","heaven",
  "herbal","heresy","hidden","hiking","hollow","honest","horror","humble","hunger","hunter",
  "hustle","ignite","impact","impose","inform","insect","inside","intent","invade","invent",
  "invest","jargon","jester","jostle","jovial","jungle","lavish","lawful","league","legend",
  "lessen","linger","little","loosen","lordly","loudly","lounge","lumber","lunacy","lurking",
  "magnet","manage","mantle","marvel","master","mature","meadow","meddle","mental","mentor",
  "middle","misery","modern","modest","moment","monkey","mortal","murder","mutter","mutual",
  "mystic","narrow","nature","needle","nestle","nettle","neural","noble","normal","notice",
  "oblige","obtain","offend","oppose","ordeal","origin","outlaw","outrun","outwit","oppose",
  "pander","pardon","parrot","patrol","patron","pebble","pester","phrase","picnic","pillar",
  "pirate","plague","planet","pledge","plenty","plunge","poison","polite","portal","potent",
  "prefer","pretty","priest","prince","prison","profit","prompt","proper","propel","prosper",
  "puddle","puzzle","quaint","quelle","rabbit","ramble","rarely","rather","ravage","reason",
  "recall","reform","refuse","relate","render","repair","repeat","rescue","resist","result",
  "retort","reveal","reward","rhythm","riddle","ripple","robust","rocket","rotten","ruckus",
  "runway","rustle","saddle","salmon","sample","savage","scheme","school","scorch","scowl",
  "scream","script","search","secret","sector","seldom","senate","settle","severe","shiver",
  "should","shrewd","shrink","signal","simple","sinker","sketch","sleuth","slight","slower",
  "smooth","solemn","soothe","sorrow","source","spirit","splash","spoken","spread","spring",
  "sprout","squall","square","squire","stable","statue","status","steady","strain","stream",
  "strict","strike","strong","struck","stunts","submit","subtle","summit","sunken","sunset",
  "surely","surmise","survey","swirls","symbol","tackle","talent","tamper","tangle","target",
  "temper","tender","theory","thieve","though","thread","threat","throne","tingle","topple",
  "torment","touchy","tragic","travel","treaty","tremble","tribal","triple","trophy","turmoil",
  "twelve","twitch","tycoon","unfair","unfold","unique","unlock","unruly","untold","uproot",
  "uptown","urgent","useful","utmost","utter","vacuum","vanish","velvet","vendor","verbal",
  "verify","victim","violent","virtue","vision","walnut","wander","warden","warmth","weapon",
  "weaken","wealth","weekly","willow","window","wisdom","wither","wonder","worthy","wounds",
  "wraith","wreath","wriggle","yogurt","zealot","zipper","zombie",
];

export function getRandomWord(difficulty: Difficulty): string {
  const list = difficulty === "easy" ? EASY : difficulty === "medium" ? MEDIUM : HARD;
  return list[Math.floor(Math.random() * list.length)].toUpperCase();
}

export function isValidGuess(word: string, difficulty: Difficulty): boolean {
  const list = difficulty === "easy" ? EASY : difficulty === "medium" ? MEDIUM : HARD;
  return list.includes(word.toLowerCase());
}
